### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by neumartin** [vladmandic/face-api#1]
Hi!
I get this error when run the code:

```
/node_modules/@vladmandic/face-api/build/index.js:1
import * as tf from '@tensorflow/tfjs-core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .js] (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/src/commons/env.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
Waiting for the debugger to disconnect...
```

My package.json is:

```
{
  "name": "monitoreo.core.server",
  "version": "1.0.0",
  "description": "Modulo Core de Reco Facial y Monitoreo Sevnt",
  "main": "dist/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow/tfjs": "^2.3.0",
    "@tensorflow/tfjs-node-gpu": "^2.3.0",
    "@types/express": "^4.17.7",
    "@vladmandic/face-api": "^0.4.1",
    "dotenv": "^8.2.0",
    "event-loop-stats": "^1.3.0",
    "express": "^4.17.1",
    "microjob": "^0.7.0",
    "rtsp-ffmpeg": "0.0.14",
    "socket.io": "^2.3.0",
    "tslib": "^1.11.1"
  },
  "devDependencies": {
    "@types/jasmine": "^3.5.14",
    "@types/node": "^13.9.2",
    "@types/socket.io": "^2.1.6",
    "canvas": "2.6.1",
    "jasmine": "^3.5.0",
    "jasmine-core": "^3.5.0",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-jasmine": "^3.1.1",
    "karma-typescript": "^5.1.0",
    "rollup": "^2.26.8",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-typescript2": "^0.26.0",
    "rollup-plugin-uglify": "^6.0.4",
    "ts-node": "^8.7.0",
    "typescript": "^3.8.3"
  }
}

```

**Comment by vladmandic** [comment]
My error in building Node module.  
I just published an updated version, should be fixed.

```js
import tf from '@tensorflow/tfjs';
import * as faceapi from '@vladmandic/face-api';
console.log('loaded tf', tf.version_core);
console.log('loaded faceapi', faceapi.tf.version_core);
```
```log
loaded tf 2.3.0
loaded faceapi 2.3.0
```

**Comment by neumartin** [comment]
@vladmandic now I get this error:
```

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/@vladmandic/face-api/dist/face-api.node.js
require() of ES modules is not supported.
require() of /home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/@vladmandic/face-api/dist/face-api.node.js from /home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/src/commons/env.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename face-api.node.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/@vladmandic/face-api/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Object.require.extensions.<computed> [as .js] (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/src/commons/env.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
Waiting for the debugger to disconnect...

```

**Comment by vladmandic** [comment]
I've pushed new version that builds CommonJS, ESM and IIFE versions of the module, so you can pick-and-choose which one to use.

I prefer to use NodeJS native `require` syntax:

```js
const tf = require('@tensorflow/tfjs');
const faceapi = require('@vladmandic/face-api');
```

NodeJS requires `"type": "module"` inside `package.json` to support `import` statements and then this works:
(note it's not `import * as x` anymore, it's `import x`)

```js
import tf from '@tensorflow/tfjs';
import faceapi from '@vladmandic/face-api';
```

Off topic, in most cases, when you see `import`, it's intended for bundlers (rollup, webpack, esbuild) to build a browser bundle and not to be executed directly, although it is picking up slowly - and causing major confusion - yet another module format.

**Comment by neumartin** [comment]
I can't make it work with Typescript, maybe a configuration issue.

I get:

```
/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/commons/faceDetection.ts(13,38): error TS2503: Cannot find namespace 'faceapi'.

    at createTSError (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/martin/Trabajo/SevntV2/src/Monitoreo.Core.Server/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
Waiting for the debugger to disconnect...
```

faceDetection.ts:
```

const tf = require('@tensorflow/tfjs');
const faceapi = require('@vladmandic/face-api');
export const faceDetectionNet = faceapi.nets.ssdMobilenetv1
// export const faceDetectionNet = tinyFaceDetector

// SsdMobilenetv1Options
const minConfidence = 0.5

// TinyFaceDetectorOptions
const inputSize = 408
const scoreThreshold = 0.5

function getFaceDetectorOptions(net: faceapi.NeuralNetwork<any>) {
  return new faceapi.SsdMobilenetv1Options({ minConfidence });
}

export const faceDetectionOptions = getFaceDetectorOptions(faceDetectionNet)

```

tsconfig.json

```
{
  "compilerOptions": {
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "ES2017",
    /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",
    /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "sourceMap": true,
    /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "dist",
    /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,
    /* Enable all strict type-checking options. */
    "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    "noImplicitThis": false,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node",
    /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": ".",                       /* Base directory to resolve non-absolute module names. */
    "paths": {
      "*": [
        "node_modules/",
        "src/types/*"
      ]
    },
    /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": false,
    /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "forceConsistentCasingInFileNames": true, /* Disallow inconsistently-cased references to the same file. */
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ]
}

```

**Comment by vladmandic** [comment]
Ah, TypeScript. My previous notes were about vanilla JS.
In TS case, yes, import is the way to go.

```js
import * as tf from '@tensorflow/tfjs';
import * as faceapi from '@vladmandic/face-api';
```
I just copied your code and it compiles out-of-the-box.

**Comment by vladmandic** [comment]
Bump...

Any update on this one?

**Comment by neumartin** [comment]
Hi!
No, finally I used the original face-api, I can't make it work.
Thanks anyway!!!

**Comment by ndtreviv** [comment]
Same issues in #6 - version just installed still doesn't enable require. What have I missed?
