### ISSUE TITLE
TypeError: backend.cast is not a function

### ISSUE THREAD

**Issue by jhfoo** [vladmandic/face-api#110]
**Issue Description**
Exception received when calling faceapi.detectAllFaces() with @tensorflow/tfjs-node:
`TypeError: backend.cast is not a function`

**Steps to Reproduce**
1. Creating working code without @tensorflow/tfjs-node
2. Added `require ('@tensorflow/tfjs-node')` at start of code after installing @tensorflow/tfjs-node

**Expected Behavior**
Faster response for detectAllFaces()

**Environment
Debian 11
Node 16.15
@tensorflow/tfjs-node 3.18.0

- Module version?
- Built-in demo or custom code?
Custom. Code snippet

```js
const faceapi = require('face-api.js')
require('@tensorflow/tfjs-node')
...
await detectFace(LocalImage, new faceapi.SsdMobilenetv1Options())

async function detectFace(img, FaceDetector) {
  const detections = await faceapi.detectAllFaces(img, FaceDetector)
}
```

- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
js

- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?
nodejs

- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)?
VM

- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?
none

**Additional**
error stack
```js
/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/ops/array_ops.js:473
    return engine_1.ENGINE.runKernelFunc(function (backend) { return backend.cast($x, dtype); }, { x: $x }, grad, 'Cast', attrs);
                                                                             ^

TypeError: backend.cast is not a function
    at engine_1.ENGINE.runKernelFunc.x (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/ops/array_ops.js:473:78)
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:528:55
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:388:22
    at Engine.scopedRun (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.tidy (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:387:21)
    at kernelFunc (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:528:29)
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:539:27
    at Engine.scopedRun (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.runKernelFunc (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/engine.js:537:14)
    at cast_ (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/ops/array_ops.js:473:28)
```
- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by jhfoo** [comment]
If I change the lines to:
```js
require('@tensorflow/tfjs-node')
const faceapi = require('face-api.js')
```
Where tfjs-node is loaded before face-api I get a different error:
```js
/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4625
                out = _this.tidy(function () { return forwardFunc_1(_this.backend, saveFunc_1); });
                                                      ^

TypeError: forwardFunc_1 is not a function
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4625:55
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4441:22
    at Engine.scopedRun (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4451:23)
    at Engine.tidy (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4440:21)
    at kernelFunc (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4625:29)
    at /home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4646:27
    at Engine.scopedRun (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4451:23)
    at Engine.runKernelFunc (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4642:14)
    at mul_ (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops.js:327:28)
    at Object.mul (/home/jhfoo/smartmirror/server/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:46:29)

```

**Comment by vladmandic** [comment]
in line `const faceapi = require('face-api.js')`, what exactly is `face-api.js`?

**Comment by jhfoo** [comment]
Thank you for the super prompt response!

Your analysis was spot-on: I switched the load order and used your repo's version of [face-api.node.js](https://github.com/vladmandic/face-api/blob/master/dist/face-api.node.js), and my code worked! It's my mistake not recognizing there's actually 2 repos for face-api:
1. https://github.com/vladmandic/face-api (yours)
2. https://github.com/justadudewhohacks/face-api.js

Thank you for continuing this work!

This is my final code
```js
require('@tensorflow/tfjs-node')
// copied from dist/
const faceapi = require('./lib/face-api.node')

```
