### ISSUE TITLE
Cant load models from uri on node.js side

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/face-api#50]
When i try to load models from node i get this error, i can load them from disc without any problem,

`await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath); // I can load`

`await faceapi.nets.faceExpressionNet.loadFromUri("http://localhost:5000/app/ai/faceapi/models/"); // cant load and get this error;`

functions: TypeError: fetch is not a function
    at fetchOrThrow (C:\Development\hemsor\ticore\node_modules\@vladmandic\face-api\dist\face-api.node.js:1513:21)
    at fetchJson (C:\Development\hemsor\ticore\node_modules\@vladmandic\face-api\dist\face-api.node.js:1532:17)
    at loadWeightMap (C:\Development\hemsor\ticore\node_modules\@vladmandic\face-api\dist\face-api.node.js:1573:26)
    at SsdMobilenetv1.loadFromUri (C:\Development\hemsor\ticore\node_modules\@vladmandic\face-api\dist\face-api.node.js:1661:29)
    at C:\Development\hemsor\functions\lib\handler\example.handler.js:121:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Development\hemsor\functions\lib\handler\example.handler.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I need to load from uri because i will put them into google function which has no disc, 

Best Regards.

**Comment by okeoke85** [comment]
Exactly as you said, thak you.
