### ISSUE TITLE
faceapi is working for me on desktop but not on mobile

### ISSUE THREAD

**Issue by deylyn** [vladmandic/face-api#57]
faceapi is working for me on desktop but not on mobile.

I am using wasm, as recommended to me and it worked perfect for a long time, both on desktop and mobil.

import * as faceapi from "@vladmandic/face-api/dist/face-api.esm.js";

 async start() {
      /**el face api solo se necesita para el selfie */
      if (this.type == "selfie") {
        await this.backendWasm();
        await this.setupFaceAPI();
      }
}
    async setupFaceAPI() {
      await faceapi.nets.tinyFaceDetector.loadFromUri("/statics/models");
    },

    async backendWasm() {
      await faceapi.tf.setWasmPaths("../statics/");
      await faceapi.tf.setBackend("wasm");
    },

for a couple of days it stopped working on mobile, will it be a question of versions of the libraries?

tensorflow
face api ??
<img width="1280" alt="Captura de Pantalla 2021-06-28 a la(s) 1 33 21 p  m" src="https://user-images.githubusercontent.com/24438895/123680798-1ac68f80-d817-11eb-8976-b7ccb69b1983.png">
<img width="1249" alt="Captura de Pantalla 2021-06-28 a la(s) 12 57 45 p  m" src="https://user-images.githubusercontent.com/24438895/123680817-2023da00-d817-11eb-92a2-4a438c6053dd.png">
<img width="1269" alt="Captura de Pantalla 2021-06-28 a la(s) 12 57 50 p  m" src="https://user-images.githubusercontent.com/24438895/123680827-21ed9d80-d817-11eb-8a29-fa7af085ddf4.png">

if you look at the first image they don't load all the wasm files, that's in mobile.

but in the other two images, if you see if they load all the files, that's on desktop

uso chrome.

 "@tensorflow/tfjs": "^3.3.0",
    "@tensorflow/tfjs-backend-wasm": "^3.3.0",
    "@vladmandic/face-api": "^1.1.12",

<img width="1280" alt="Captura de Pantalla 2021-06-28 a la(s) 1 29 27 p  m" src="https://user-images.githubusercontent.com/24438895/123680440-b60b3500-d816-11eb-8a79-913bf5f4d763.png">

**Comment by vladmandic** [comment]
just for troubleshooting, can you try to disable SIMD flag on mobile? it seems it's loading `tfjs-backend-wasm-simd.wasm` and i'd like to know what happens if it loads regular WASM binary.

on desktop, it's loading `tfjs-backend-wasm-threaded-simd` because you have explicitly enabled multi-threading support - and because of that, you see how 8 threads are being created.

anyhow, i don't think this is related to specific version of the library - although i do recommend to try with the latest version.

what is likely is changes in behavior on chrome side - google is currently changing security model around WASM loading and it is causing a lot of issues starting a process from a loaded WASM file. and in your case, chrome likely got auto-updated and it caused issues. can you confirm exact versions of chrome you're using on both desktop and mobile.

**Comment by deylyn** [comment]
where do i find the wasm binary?

I do not think it is the chrome that is affecting because I have two environments, one for production and one for development, and in the production one it still works perfect both on desktop and mobile, it does not work on mobile it is in development, I could have updated some other external library that directly affects faceapi? like jquery or another ??

**Comment by deylyn** [comment]
update the libraries to @ vladmandic / face-api
1.3.1

and it gives this warning when I compile

WARNING Compiled with 1 warnings 14:26:11

 warning in ./node_modules/@vladmandic/face-api/dist/face-api.esm.js

Critical dependency: the request of a dependency is an expression

and this error when I test it

<img width="1280" alt="Captura de Pantalla 2021-06-29 a la(s) 2 30 11 p  m" src="https://user-images.githubusercontent.com/24438895/123849232-8cb9da00-d8e6-11eb-815a-0bc68890b1d0.png">

**Comment by vladmandic** [comment]
> I do not think it is the chrome that is affecting because I have two environments, one for production and one for development, and in the production one it still works perfect both on desktop and mobile, it does not work on mobile it is in development, I could have updated some other external library that directly affects faceapi? like jquery or another ??

With this error, I still believe its a combination of HTTP headers set by your web server and specific browser version.  
And the warnings regarding `SharedArrayBuffer` mean exactly that - your web server should set explicit header flags to be compatible with latest Chrome or browser will refuse to load WASM binaries.

But regarding `Cannot read property 'apply' of undefined`  - I haven't seen that before. Unfortunately, your backtrace is too short so I can't see where error starts - can you expand it further?

**Comment by vladmandic** [comment]
Any updates?

**Comment by nazzour** [comment]
Hello, I am having a similar issue. For Desktop, my app is working just fine. when I run it on iOS I am having the webGL issue (Could not get context for webGL version 2) for both chrome and safari. I am actually using wasm to solve the issue like the follwoing:

`
await faceapi.tf.setWasmPaths("../node_modules/@tensorflow/tfjs-backend-wasm/dist/");
await faceapi.tf.setBackend("wasm");
`
However I ma geting the following error 

> Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info. ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
    at abort (face-api.esm.js:3205)
    at getBinary (face-api.esm.js:3235)
    at face-api.esm.js:3247
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569) RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:4200/main.js:3350:19)
    at getBinary (https://localhost:4200/main.js:3380:13)
    at https://localhost:4200/main.js:3392:24
    at ZoneDelegate.invoke (https://localhost:4200/polyfills.js:9611:30)
    at Zone.run (https://localhost:4200/polyfills.js:9370:47)
    at https://localhost:4200/polyfills.js:10104:40
    at ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:9646:35)
    at Zone.runTask (https://localhost:4200/polyfills.js:9414:51)
    at drainMicroTaskQueue (https://localhost:4200/polyfills.js:9816:39)

Any help please ?

**Comment by deylyn** [comment]
> Hello, I am having a similar issue. For Desktop, my app is working just fine. when I run it on iOS I am having the webGL issue (Could not get context for webGL version 2) for both chrome and safari. I am actually using wasm to solve the issue like the follwoing:
> 
> `await faceapi.tf.setWasmPaths("../node_modules/@tensorflow/tfjs-backend-wasm/dist/"); await faceapi.tf.setBackend("wasm");`
> However I ma geting the following error
> 
> > Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info. ; Zone:  ; Task: Promise.then ; Value: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > at abort (face-api.esm.js:3205)
> > at getBinary (face-api.esm.js:3235)
> > at face-api.esm.js:3247
> > at ZoneDelegate.invoke (zone-evergreen.js:364)
> > at Zone.run (zone-evergreen.js:123)
> > at zone-evergreen.js:857
> > at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> > at Zone.runTask (zone-evergreen.js:167)
> > at drainMicroTaskQueue (zone-evergreen.js:569) RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > at abort (https://localhost:4200/main.js:3350:19)
> > at getBinary (https://localhost:4200/main.js:3380:13)
> > at https://localhost:4200/main.js:3392:24
> > at ZoneDelegate.invoke (https://localhost:4200/polyfills.js:9611:30)
> > at Zone.run (https://localhost:4200/polyfills.js:9370:47)
> > at https://localhost:4200/polyfills.js:10104:40
> > at ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:9646:35)
> > at Zone.runTask (https://localhost:4200/polyfills.js:9414:51)
> > at drainMicroTaskQueue (https://localhost:4200/polyfills.js:9816:39)
> 
> Any help please ?

In my case, faceapi did not work correctly, it was because before using it in the previous step, the camera did not close properly and that affected it in some way. I mean, I didn't have to do something different with faceapi to get it to work correctly again

**Comment by nazzour** [comment]
> > Hello, I am having a similar issue. For Desktop, my app is working just fine. when I run it on iOS I am having the webGL issue (Could not get context for webGL version 2) for both chrome and safari. I am actually using wasm to solve the issue like the follwoing:
> > `await faceapi.tf.setWasmPaths("../node_modules/@tensorflow/tfjs-backend-wasm/dist/"); await faceapi.tf.setBackend("wasm");`
> > However I ma geting the following error
> > > Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info. ; Zone:  ; Task: Promise.then ; Value: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > at abort (face-api.esm.js:3205)
> > > at getBinary (face-api.esm.js:3235)
> > > at face-api.esm.js:3247
> > > at ZoneDelegate.invoke (zone-evergreen.js:364)
> > > at Zone.run (zone-evergreen.js:123)
> > > at zone-evergreen.js:857
> > > at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> > > at Zone.runTask (zone-evergreen.js:167)
> > > at drainMicroTaskQueue (zone-evergreen.js:569) RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > at abort (https://localhost:4200/main.js:3350:19)
> > > at getBinary (https://localhost:4200/main.js:3380:13)
> > > at https://localhost:4200/main.js:3392:24
> > > at ZoneDelegate.invoke (https://localhost:4200/polyfills.js:9611:30)
> > > at Zone.run (https://localhost:4200/polyfills.js:9370:47)
> > > at https://localhost:4200/polyfills.js:10104:40
> > > at ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:9646:35)
> > > at Zone.runTask (https://localhost:4200/polyfills.js:9414:51)
> > > at drainMicroTaskQueue (https://localhost:4200/polyfills.js:9816:39)
> > 
> > 
> > Any help please ?
> 
> In my case, faceapi did not work correctly, it was because before using it in the previous step, the camera did not close properly and that affected it in some way. I mean, I didn't have to do something different with faceapi to get it to work correctly again

Thank you for the reply, in my case maybe it can be a typescript problem ?

**Comment by deylyn** [comment]
> > > Hello, I am having a similar issue. For Desktop, my app is working just fine. when I run it on iOS I am having the webGL issue (Could not get context for webGL version 2) for both chrome and safari. I am actually using wasm to solve the issue like the follwoing:
> > > `await faceapi.tf.setWasmPaths("../node_modules/@tensorflow/tfjs-backend-wasm/dist/"); await faceapi.tf.setBackend("wasm");`
> > > However I ma geting the following error
> > > > Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info. ; Zone:  ; Task: Promise.then ; Value: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > > at abort (face-api.esm.js:3205)
> > > > at getBinary (face-api.esm.js:3235)
> > > > at face-api.esm.js:3247
> > > > at ZoneDelegate.invoke (zone-evergreen.js:364)
> > > > at Zone.run (zone-evergreen.js:123)
> > > > at zone-evergreen.js:857
> > > > at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> > > > at Zone.runTask (zone-evergreen.js:167)
> > > > at drainMicroTaskQueue (zone-evergreen.js:569) RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > > at abort (https://localhost:4200/main.js:3350:19)
> > > > at getBinary (https://localhost:4200/main.js:3380:13)
> > > > at https://localhost:4200/main.js:3392:24
> > > > at ZoneDelegate.invoke (https://localhost:4200/polyfills.js:9611:30)
> > > > at Zone.run (https://localhost:4200/polyfills.js:9370:47)
> > > > at https://localhost:4200/polyfills.js:10104:40
> > > > at ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:9646:35)
> > > > at Zone.runTask (https://localhost:4200/polyfills.js:9414:51)
> > > > at drainMicroTaskQueue (https://localhost:4200/polyfills.js:9816:39)
> > > 
> > > 
> > > Any help please ?
> > 
> > 
> > In my case, faceapi did not work correctly, it was because before using it in the previous step, the camera did not close properly and that affected it in some way. I mean, I didn't have to do something different with faceapi to get it to work correctly again
> 
> Thank you for the reply, in my case maybe it can be a typescript problem ?

It could be, if you look at the beginning of the issue I show how I am implementing it and it seems that you are working the same

**Comment by nazzour** [comment]
> > > > Hello, I am having a similar issue. For Desktop, my app is working just fine. when I run it on iOS I am having the webGL issue (Could not get context for webGL version 2) for both chrome and safari. I am actually using wasm to solve the issue like the follwoing:
> > > > `await faceapi.tf.setWasmPaths("../node_modules/@tensorflow/tfjs-backend-wasm/dist/"); await faceapi.tf.setBackend("wasm");`
> > > > However I ma geting the following error
> > > > > Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info. ; Zone:  ; Task: Promise.then ; Value: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > > > at abort (face-api.esm.js:3205)
> > > > > at getBinary (face-api.esm.js:3235)
> > > > > at face-api.esm.js:3247
> > > > > at ZoneDelegate.invoke (zone-evergreen.js:364)
> > > > > at Zone.run (zone-evergreen.js:123)
> > > > > at zone-evergreen.js:857
> > > > > at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> > > > > at Zone.runTask (zone-evergreen.js:167)
> > > > > at drainMicroTaskQueue (zone-evergreen.js:569) RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
> > > > > at abort (https://localhost:4200/main.js:3350:19)
> > > > > at getBinary (https://localhost:4200/main.js:3380:13)
> > > > > at https://localhost:4200/main.js:3392:24
> > > > > at ZoneDelegate.invoke (https://localhost:4200/polyfills.js:9611:30)
> > > > > at Zone.run (https://localhost:4200/polyfills.js:9370:47)
> > > > > at https://localhost:4200/polyfills.js:10104:40
> > > > > at ZoneDelegate.invokeTask (https://localhost:4200/polyfills.js:9646:35)
> > > > > at Zone.runTask (https://localhost:4200/polyfills.js:9414:51)
> > > > > at drainMicroTaskQueue (https://localhost:4200/polyfills.js:9816:39)
> > > > 
> > > > 
> > > > Any help please ?
> > > 
> > > 
> > > In my case, faceapi did not work correctly, it was because before using it in the previous step, the camera did not close properly and that affected it in some way. I mean, I didn't have to do something different with faceapi to get it to work correctly again
> > 
> > 
> > Thank you for the reply, in my case maybe it can be a typescript problem ?
> 
> It could be, if you look at the beginning of the issue I show how I am implementing it and it seems that you are working the same

Yes, I am using angular and this is the unique difference

**Comment by deylyn** [comment]
I am using Vue

**Comment by vladmandic** [comment]
@deylyn and @nazzour, please fill exactly which combination is working and which has problems - I'm having a hard time following this thread.
min information needed is: os, browser, backend, framework, web server

and if it used to work, but stopped working note what has changed? e.g. version of browser, etc.

having said that, frameworks that precompile code should be configured so faceapi library is excluded from the default bundler.
at the very minimum, error `Critical dependency: the request of a dependency is an expression` comes from a bundler - and i cannot troubleshoot what some third party bundler does.

which means you're not using pure vue/angular, but some dev web server with hot-module-reload and bunder functionality.

also, warning regarding `SharedArrayBuffer` is due to dev web server that you're using - it does not send correct HTTP headers that are required by latest versions of browwsers. 

and no, it's not a *typescript* problem is you're using `face-api.esm.js` since that is already a bundle compiled in js es2018 format, not typescript (you might have issues with *typescript* if you're loading library from `src/index.ts`, not if you're loading ESM module).

regarding error `Unhandled Promise rejection: abort(both async and sync fetching of the wasm failed).` - can you check network tab in the browser inspector and see if http request is fulfilled by web server. it could be as trivial as web server not serving those files or not having correct permissions.

btw, i'm traveling for the next 10 days so my replies will be slower that ideal.

**Comment by vladmandic** [comment]
@deylyn & @nazzour any updates?

**Comment by vladmandic** [comment]
closing due to inactivity  
if new information is provided, issue can be reopened
